spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RestaurantManagement_DB
    username: root
    password: Ta@190403
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true

server:
  port: 8080
